Change kcov Travis script newline lines to accommodate YAML's maintenance of existing newlines in string

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,26 +47,29 @@ script:
   - cargo test
 
 # Required for code coverage with kcov and codecov.io
-# Taken from: https://github.com/codecov/example-rust
+# Adapted from: https://github.com/codecov/example-rust
 after_success: |
-  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
-      && tar xzf master.tar.gz
-      && cd kcov-master
-      && mkdir build
-      && cd build
-      && cmake ..
-      && make
-      && make install DESTDIR=../../kcov-build
-      && cd ../..
-      && rm -rf kcov-master
-      && for file in target/debug/sylan-*;
+  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz \
+      && tar xzf master.tar.gz \
+      && cd kcov-master \
+      && mkdir build \
+      && cd build \
+      && cmake .. \
+      && make \
+      && make install DESTDIR=../../kcov-build \
+      && cd ../.. \
+      && rm -rf kcov-master \
+      && for file in target/debug/sylan-*
       do
-          mkdir -p "target/cov/$(basename $file)"
-              && ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file";
-          if [ "$0" != 0 ];
+          mkdir -p "target/cov/$(basename $file)" \
+              && ./kcov-build/usr/local/bin/kcov \
+                  --exclude-pattern=/.cargo,/usr/lib \
+                  --verify "target/cov/$(basename $file)" \
+                  "$file"
+          if [ "$0" != 0 ]
           then
-              echo "failed kcov";
-              exit 1;
-          fi;
-      done
+              echo "failed kcov"
+              exit 1
+          fi
+      done \
       && bash <(curl -s https://codecov.io/bash)
